version: '2.4'


services:
  bicycle-store-server:
    container_name: 
        bicycle-store-server
    build:
      context: ./server
    restart: always
    ports:
      - 9000:9000
    networks: 
      bicycle-network:
        aliases:
          - bicycle-store-server

  bicycle-store-web:
    container_name: 
        bicycle-store-web
    build:
      context: ./web
    restart: always
    ports:
      - 5000:5000
    networks: 
      bicycle-network:
        aliases:
          - bicycle-store-server

networks: 
    bicycle-network:
        external: true
